using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Text;

namespace Entities.Configuration
{
    class FactuurConfiguration : IEntityTypeConfiguration<Factuur>
    {
        public void Configure(EntityTypeBuilder<Factuur> builder)
        {
            
            builder.HasData(
            new Factuur
            {
                FactuurNr = 1, //FactuurNr autogenerated PK
                ContactId = 1,
                Bedrag = 260,
                Btwtarief = 6,
                Status = "Open",
                Type = 1,
                Omschrijving = "Tafel",
                FactuurDatum = new DateTime(2020, 6, 2),
                BetaalDatum = default
            },

            new Factuur
            {
                FactuurNr = 2, //FactuurNr autogenerated PK
                ContactId = 3,
                Bedrag = 450,
                Btwtarief = 21,
                Status = "Betaald",
                Type = 1,
                Omschrijving = "Herstoffering",
                FactuurDatum = new DateTime(2020, 7, 25),
                BetaalDatum = new DateTime(2020, 6, 3)
            },

            new Factuur
            {
                FactuurNr = 3, //FactuurNr autogenerated PK
                ContactId = 5,
                Bedrag = 120,
                Btwtarief = 6,
                Status = "Betaald",
                Type = 2,
                Omschrijving = "Kast",
                FactuurDatum = new DateTime(2020, 7, 10),
                BetaalDatum = new DateTime(2020, 07, 02)
            },

            new Factuur
            {
                FactuurNr = 4, //FactuurNr autogenerated PK
                ContactId = 6,
                Bedrag = 600,
                Btwtarief = 6,
                Status = "Open",
                Type = 2,
                Omschrijving = "Telecom installatie",
                FactuurDatum = new DateTime(2020, 1, 20),
                BetaalDatum = default
            }


            );
        }
    }
}
