using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Text;

namespace Entities.Configuration
{
    class LeverancierConfiguration : IEntityTypeConfiguration<Leverancier>
    {
        public void Configure(EntityTypeBuilder<Leverancier> builder)
        {
            builder.HasData(
                new Leverancier
                {
                    LeverancierNr =1,//ContactNr FK van autogenerated Contact
                    NaamBedrijf = "HR-Rail"
                },
                 new Leverancier
                 {
                     LeverancierNr = 2,
                     NaamBedrijf = "Proximus"
                 },

                  new Leverancier
                  {
                      LeverancierNr = 3,
                      NaamBedrijf = "KBC"
                  },

                  new Leverancier
                  {
                      LeverancierNr = 4,
                      NaamBedrijf = "Standaard Boekhandel"
                  }
                );           
        }
    }
}
